[package]
name = "rsa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
factor = "0.4.0"
primes = "0.3.0"
primefactor = "0.1.2"